# Import all dependencies

In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import sqlite3

# Load .csv files

In [2]:
import os
import pandas as pd

print("Current Working Directory:")
print(os.getcwd())

print("\nCSV Files Found:\n")

for root, dirs, files in os.walk("."):
    for file in files:
        if file.endswith(".csv"):
            print(os.path.join(root, file))

Current Working Directory:
c:\Users\User\OneDrive\Desktop\Mutual_Fund_Analytics\notebooks

CSV Files Found:

In [3]:
import os

print("Folders in project root:\n")

for item in os.listdir(".."):
    print(item)

Folders in project root:

.git
dashboard
data
data_ingestion.py
live_nav_fetch.py
notebooks
README.md
reports
requirements.txt
sql

In [4]:
import os

for root, dirs, files in os.walk(".."):
    for file in files:
        if file.endswith(".csv"):
            print(os.path.join(root, file))

..\data\processed\01_fund_master.csv
..\data\processed\02_nav_history.csv
..\data\processed\03_aum_by_fund_house.csv
..\data\processed\04_monthly_sip_inflows.csv
..\data\processed\05_category_inflows.csv
..\data\processed\06_industry_folio_count.csv
..\data\processed\07_scheme_performance.csv
..\data\processed\08_investor_transactions.csv
..\data\processed\09_portfolio_holdings.csv
..\data\processed\10_benchmark_indices.csv
..\data\raw\Axis_Bluechip_nav.csv
..\data\raw\HDFC_Top100_nav.csv
..\data\raw\ICICI_Bluechip_nav.csv
..\data\raw\Kotak_Bluechip_nav.csv
..\data\raw\Nippon_LargeCap_nav.csv
..\data\raw\SBI_Bluechip_nav.csv

In [5]:
fund_master = pd.read_csv(r"C:\Users\User\Mutual_fund_analysis\data\processed\01_fund_master.csv")

nav_history = pd.read_csv(r"C:\Users\User\Mutual_fund_analysis\data\processed\02_nav_history.csv")

aum = pd.read_csv(r"C:\Users\User\Mutual_fund_analysis\data\processed\03_aum_by_fund_house.csv")

sip = pd.read_csv(r"C:\Users\User\Mutual_fund_analysis\data\processed\04_monthly_sip_inflows.csv")

category = pd.read_csv(r"C:\Users\User\Mutual_fund_analysis\data\processed\05_category_inflows.csv")

folio = pd.read_csv(r"C:\Users\User\Mutual_fund_analysis\data\processed\06_industry_folio_count.csv")

performance = pd.read_csv(r"C:\Users\User\Mutual_fund_analysis\data\processed\07_scheme_performance.csv")

transactions = pd.read_csv(r"C:\Users\User\Mutual_fund_analysis\data\processed\08_investor_transactions.csv")

holdings = pd.read_csv(r"C:\Users\User\Mutual_fund_analysis\data\processed\09_portfolio_holdings.csv")

benchmark = pd.read_csv(r"C:\Users\User\Mutual_fund_analysis\data\processed\10_benchmark_indices.csv")

print("All CSV files loaded successfully")

All CSV files loaded successfully

# analysis

In [6]:
print("Fund Master:", fund_master.shape)
print("NAV History:", nav_history.shape)
print("AUM:", aum.shape)
print("SIP:", sip.shape)
print("Category:", category.shape)
print("Folio:", folio.shape)
print("Performance:", performance.shape)
print("Transactions:", transactions.shape)
print("Holdings:", holdings.shape)
print("Benchmark:", benchmark.shape)

Fund Master: (40, 15)
NAV History: (46000, 3)
AUM: (90, 5)
SIP: (48, 6)
Category: (144, 3)
Folio: (21, 6)
Performance: (40, 19)
Transactions: (32778, 13)
Holdings: (322, 8)
Benchmark: (8050, 3)

# Missing Values (isnull())

In [7]:
datasets = {
    "Fund Master": fund_master,
    "NAV History": nav_history,
    "AUM": aum,
    "SIP": sip,
    "Category": category,
    "Folio": folio,
    "Performance": performance,
    "Transactions": transactions,
    "Holdings": holdings,
    "Benchmark": benchmark
}

for name, df in datasets.items():
    print("\n" + "="*60)
    print(name)
    print("="*60)
    print(df.isnull().sum())

============================================================
Fund Master
============================================================
amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

============================================================
NAV History
============================================================
amfi_code    0
date         0
nav          0
dtype: int64

============================================================
AUM
============================================================
date              0
fund_house        0
aum_lakh_crore    0
aum_crore         0
num_schemes       0
dtype: int64

============================================================
SIP
============================================================
month                         0
sip_inflow_crore              0
active_sip_accounts_crore     0
new_sip_accounts_lakh         0
sip_aum_lakh_crore            0
yoy_growth_pct               12
dtype: int64

============================================================
Category
============================================================
month               0
category            0
net_inflow_crore    0
dtype: int64

============================================================
Folio
============================================================
month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64

============================================================
Performance
============================================================
amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

============================================================
Transactions
============================================================
investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

============================================================
Holdings
============================================================
amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
portfolio_date       0
dtype: int64

============================================================
Benchmark
============================================================
date           0
index_name     0
close_value    0
dtype: int64

# Duplicate Rows

In [8]:
datasets = {
    "Fund Master": fund_master,
    "NAV History": nav_history,
    "AUM": aum,
    "SIP": sip,
    "Category": category,
    "Folio": folio,
    "Performance": performance,
    "Transactions": transactions,
    "Holdings": holdings,
    "Benchmark": benchmark
}

for name, df in datasets.items():
    print("\n" + "="*60)
    print(name)
    print("="*60)
    print("Duplicate Rows:", df.duplicated().sum())

============================================================
Fund Master
============================================================
Duplicate Rows: 0

============================================================
NAV History
============================================================
Duplicate Rows: 0

============================================================
AUM
============================================================
Duplicate Rows: 0

============================================================
SIP
============================================================
Duplicate Rows: 0

============================================================
Category
============================================================
Duplicate Rows: 0

============================================================
Folio
============================================================
Duplicate Rows: 0

============================================================
Performance
============================================================
Duplicate Rows: 0

============================================================
Transactions
============================================================

Duplicate Rows: 0

============================================================
Holdings
============================================================
Duplicate Rows: 0

============================================================
Benchmark
============================================================
Duplicate Rows: 0

# Check Data Types

In [9]:
datasets = {
    "Fund Master": fund_master,
    "NAV History": nav_history,
    "AUM": aum,
    "SIP": sip,
    "Category": category,
    "Folio": folio,
    "Performance": performance,
    "Transactions": transactions,
    "Holdings": holdings,
    "Benchmark": benchmark
}

for name, df in datasets.items():
    print("\n" + "="*60)
    print(name)
    print("="*60)
    print(df.dtypes)

============================================================
Fund Master
============================================================
amfi_code               int64
fund_house             object
scheme_name            object
category               object
sub_category           object
plan                   object
launch_date            object
benchmark              object
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager           object
risk_category          object
sebi_category_code     object
dtype: object

============================================================
NAV History
============================================================
amfi_code      int64
date          object
nav          float64
dtype: object

============================================================
AUM
============================================================
date               object
fund_house         object
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object

============================================================
SIP
============================================================
month                         object
sip_inflow_crore               int64
active_sip_accounts_crore    float64
new_sip_accounts_lakh        float64
sip_aum_lakh_crore           float64
yoy_growth_pct               float64
dtype: object

============================================================
Category
============================================================
month                object
category             object
net_inflow_crore    float64
dtype: object

============================================================
Folio
============================================================
month                   object
total_folios_crore     float64
equity_folios_crore    float64
debt_folios_crore      float64
hybrid_folios_crore    float64
others_folios_crore    float64
dtype: object

============================================================
Performance
============================================================
amfi_code               int64
scheme_name            object
fund_house             object
category               object
plan                   object
return_1yr_pct        float64
return_3yr_pct        float64
return_5yr_pct        float64
benchmark_3yr_pct     float64
alpha                 float64
beta                  float64
sharpe_ratio          float64
sortino_ratio         float64
std_dev_ann_pct       float64
max_drawdown_pct      float64
aum_crore               int64
expense_ratio_pct     float64
morningstar_rating      int64
risk_grade             object
dtype: object

============================================================
Transactions
============================================================
investor_id            object
transaction_date       object
amfi_code               int64
transaction_type       object
amount_inr              int64
state                  object
city                   object
city_tier              object
age_group              object
gender                 object
annual_income_lakh    float64
payment_mode           object
kyc_status             object
dtype: object

============================================================
Holdings
============================================================
amfi_code              int64
stock_symbol          object
stock_name            object
sector                object
weight_pct           float64
market_value_cr      float64
current_price_inr    float64
portfolio_date        object
dtype: object

============================================================
Benchmark
============================================================
date            object
index_name      object
close_value    float64
dtype: object

# Check First 5 Rows of All Tables

In [10]:
datasets = {
    "Fund Master": fund_master,
    "NAV History": nav_history,
    "AUM": aum,
    "SIP": sip,
    "Category": category,
    "Folio": folio,
    "Performance": performance,
    "Transactions": transactions,
    "Holdings": holdings,
    "Benchmark": benchmark
}

for name, df in datasets.items():
    print("\n" + "="*60)
    print(name)
    print("="*60)
    display(df.head())

============================================================
Fund Master
============================================================

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

============================================================
NAV History
============================================================

   amfi_code        date      nav
0     119551  2022-01-03  54.3856
1     119551  2022-01-04  54.3474
2     119551  2022-01-05  54.6869
3     119551  2022-01-06  55.4550
4     119551  2022-01-07  55.3692

============================================================
AUM
============================================================

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

============================================================
SIP
============================================================

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN

============================================================
Category
============================================================

     month         category  net_inflow_crore
0  2024-04        Large Cap            2413.0
1  2024-04          Mid Cap            3897.0
2  2024-04        Small Cap            3533.0
3  2024-04        Flexi Cap            4947.0
4  2024-04  Large & Mid Cap            4214.0

============================================================
Folio
============================================================

,month,total_folios_crore,equity_folios_crore,debt_folios_crore,hybrid_folios_crore,others_folios_crore
0,2022-01,13.26,9.28,1.86,0.80,1.33
1,2022-04,13.91,9.74,1.95,0.83,1.39
2,2022-07,13.85,9.69,1.94,0.83,1.38
3,2022-10,14.12,9.88,1.98,0.85,1.41
4,2023-01,14.81,10.37,2.07,0.89,1.48

============================================================
Performance
============================================================

,amfi_code,scheme_name,fund_house,category,plan,return_1yr_pct,return_3yr_pct,return_5yr_pct,benchmark_3yr_pct,alpha,beta,sharpe_ratio,sortino_ratio,std_dev_ann_pct,max_drawdown_pct,aum_crore,expense_ratio_pct,morningstar_rating,risk_grade
0,119551,SBI Bluechip Fund - Regular Plan - Growth,SBI Mutual Fund,Large Cap,Regular,12.42,12.36,14.45,11.49,0.87,0.89,0.88,1.29,14.0,-21.70,14288,1.54,4,Moderate
1,119552,SBI Bluechip Fund - Direct Plan - Growth,SBI Mutual Fund,Large Cap,Direct,15.25,11.30,14.23,9.52,1.78,0.87,0.81,1.29,14.0,-24.43,1231,0.66,3,Moderate
2,119598,SBI Small Cap Fund - Regular Plan - Growth,SBI Mutual Fund,Small Cap,Regular,24.56,23.39,20.67,22.16,1.23,0.89,0.94,1.35,25.0,-13.35,19259,1.43,5,Very High
3,119599,SBI Small Cap Fund - Direct Plan - Growth,SBI Mutual Fund,Small Cap,Direct,20.59,23.14,21.82,22.01,1.13,1.04,0.93,1.67,25.0,-24.78,36061,0.72,4,Very High
4,119120,SBI Magnum Gilt Fund - Regular Plan - Growth,SBI Mutual Fund,Gilt,Regular,5.34,6.07,5.43,4.47,1.60,0.22,1.52,2.11,4.0,-2.30,24101,0.77,5,Low

============================================================
Transactions
============================================================

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

============================================================
Holdings
============================================================

,amfi_code,stock_symbol,stock_name,sector,weight_pct,market_value_cr,current_price_inr,portfolio_date
0,119551,POWERGRID,Power Grid Corporation,Utilities,13.85,737.09,6011.08,2025-12-31
1,119551,HDFCBANK,HDFC Bank Ltd,Banking,11.19,88.97,1074.65,2025-12-31
2,119551,GRASIM,Grasim Industries Ltd,Diversified,9.90,208.45,5964.59,2025-12-31
3,119551,DRREDDY,Dr. Reddy's Laboratories,Pharma,4.76,161.32,3748.82,2025-12-31
4,119551,ASIANPAINT,Asian Paints Ltd,Paints,10.25,725.90,1321.45,2025-12-31

============================================================
Benchmark
============================================================

         date index_name  close_value
0  2022-01-03    NIFTY50     17492.79
1  2022-01-04    NIFTY50     17689.64
2  2022-01-05    NIFTY50     17835.05
3  2022-01-06    NIFTY50     17878.51
4  2022-01-07    NIFTY50     17759.15

In [11]:
transactions['transaction_date'] = pd.to_datetime(
    transactions['transaction_date']
)

transactions = transactions[
    transactions['amount_inr'] > 0
]

transactions['transaction_type'] = (
    transactions['transaction_type']
    .str.strip()
)

In [12]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  object
 1   transaction_date    32778 non-null  datetime64[ns]
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  object
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  object
 6   city                32778 non-null  object
 7   city_tier           32778 non-null  object
 8   age_group           32778 non-null  object
 9   gender              32778 non-null  object
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  object
 12  kyc_status          32778 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(9)
memory usage: 3.3+ MB

In [13]:
performance['return_1yr_pct'] = pd.to_numeric(
    performance['return_1yr_pct'],
    errors='coerce'
)

performance['sharpe_ratio'] = pd.to_numeric(
    performance['sharpe_ratio'],
    errors='coerce'
)

In [14]:
performance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     object
 2   fund_house          40 non-null     object
 3   category            40 non-null     object
 4   plan                40 non-null     object
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     object
dtypes: float64(11), int64(3), object(5)
memory usage: 6.1+ KB

In [15]:
nav_history.to_csv(
    "../data/processed/clean_nav.csv",
    index=False
)

transactions.to_csv(
    "../data/processed/clean_transactions.csv",
    index=False
)

performance.to_csv(
    "../data/processed/clean_performance.csv",
    index=False
)

In [16]:
engine = create_engine(
    "sqlite:///bluestock_mf.db"
)

# Clean all 10 .csv file

## 1. Clean 01_fund_master.csv

In [17]:
# Remove duplicates
fund_master = fund_master.drop_duplicates()

# Remove spaces
text_cols = ['fund_house','scheme_name','category','sub_category',
             'plan','benchmark','fund_manager',
             'risk_category','sebi_category_code']

for col in text_cols:
    fund_master[col] = fund_master[col].astype(str).str.strip()

# Convert date
fund_master['launch_date'] = pd.to_datetime(
    fund_master['launch_date'],
    errors='coerce'
)

# Numeric columns
numeric_cols = [
    'expense_ratio_pct',
    'exit_load_pct',
    'min_sip_amount',
    'min_lumpsum_amount'
]

for col in numeric_cols:
    fund_master[col] = pd.to_numeric(
        fund_master[col],
        errors='coerce'
    )

# Remove duplicate AMFI codes
fund_master = fund_master.drop_duplicates(subset='amfi_code')

# Validate expense ratio
fund_master = fund_master[
    fund_master['expense_ratio_pct'].between(0.1,2.5)
]

fund_master.to_csv(
    "../data/processed/clean_fund_master.csv",
    index=False
)

## 2. Clean 02_nav_history.csv

In [18]:
nav_history['date'] = pd.to_datetime(
    nav_history['date'],
    errors='coerce'
)

nav_history = nav_history.sort_values(
    ['amfi_code','date']
)

nav_history = nav_history.drop_duplicates()

nav_history['nav'] = (
    nav_history.groupby('amfi_code')['nav']
    .ffill()
)

nav_history = nav_history[
    nav_history['nav'] > 0
]

nav_history.to_csv(
    "../data/processed/clean_nav_history.csv",
    index=False
)

## 3. Clean 03_aum_by_fund_house.csv

In [19]:
aum = aum.drop_duplicates()

aum['date'] = pd.to_datetime(
    aum['date'],
    errors='coerce'
)

aum['fund_house'] = (
    aum['fund_house']
    .str.strip()
)

numeric_cols = [
    'aum_lakh_crore',
    'aum_crore',
    'num_schemes'
]

for col in numeric_cols:
    aum[col] = pd.to_numeric(
        aum[col],
        errors='coerce'
    )

    aum = aum[aum[col] >= 0]

aum.to_csv(
    "../data/processed/clean_aum_by_fund_house.csv",
    index=False
)

## 4. Clean 04_monthly_sip_inflows.csv

In [20]:
sip = sip.drop_duplicates()

sip['month'] = pd.to_datetime(
    sip['month'],
    errors='coerce'
)

cols = [
    'sip_inflow_crore',
    'active_sip_accounts_crore',
    'new_sip_accounts_lakh',
    'sip_aum_lakh_crore',
    'yoy_growth_pct'
]

for col in cols:
    sip[col] = pd.to_numeric(
        sip[col],
        errors='coerce'
    )

sip.to_csv(
    "../data/processed/clean_monthly_sip_inflows.csv",
    index=False
)

## 5. Clean 05_category_inflows.csv

In [21]:
category = category.drop_duplicates()

category['month'] = pd.to_datetime(
    category['month'],
    errors='coerce'
)

category['category'] = (
    category['category']
    .str.strip()
)

category['net_inflow_crore'] = pd.to_numeric(
    category['net_inflow_crore'],
    errors='coerce'
)

category.to_csv(
    "../data/processed/clean_category_inflows.csv",
    index=False
)

## 6. Clean 06_industry_folio_count.csv

In [22]:
folio = folio.drop_duplicates()

folio['month'] = pd.to_datetime(
    folio['month'],
    errors='coerce'
)

cols = [
    'total_folios_crore',
    'equity_folios_crore',
    'debt_folios_crore',
    'hybrid_folios_crore',
    'others_folios_crore'
]

for col in cols:
    folio[col] = pd.to_numeric(
        folio[col],
        errors='coerce'
    )

folio.to_csv(
    "../data/processed/clean_industry_folio_count.csv",
    index=False
)

## 7. Clean 07_scheme_performance.csv

In [23]:
performance = performance.drop_duplicates()

numeric_cols = [
    'return_1yr_pct',
    'return_3yr_pct',
    'return_5yr_pct',
    'benchmark_3yr_pct',
    'alpha',
    'beta',
    'sharpe_ratio',
    'sortino_ratio',
    'std_dev_ann_pct',
    'max_drawdown_pct',
    'aum_crore',
    'expense_ratio_pct'
]

for col in numeric_cols:
    performance[col] = pd.to_numeric(
        performance[col],
        errors='coerce'
    )

# Flag negative Sharpe
negative_sharpe = performance[
    performance['sharpe_ratio'] < 0
]

print(negative_sharpe)

performance = performance[
    performance['expense_ratio_pct'].between(0.1,2.5)
]

performance.to_csv(
    "../data/processed/clean_scheme_performance.csv",
    index=False
)

Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

## 8. Clean 08_investor_transactions.csv

In [24]:
transactions = transactions.drop_duplicates()

transactions['transaction_date'] = pd.to_datetime(
    transactions['transaction_date'],
    errors='coerce'
)

transactions['transaction_type'] = (
    transactions['transaction_type']
    .str.strip()
    .str.title()
)

transactions = transactions[
    transactions['transaction_type'].isin(
        ['Sip','Lumpsum','Redemption']
    )
]

transactions = transactions[
    transactions['amount_inr'] > 0
]

transactions = transactions[
    transactions['kyc_status'].isin(
        ['Verified','Pending']
    )
]

transactions.to_csv(
    "../data/processed/clean_investor_transactions.csv",
    index=False
)

## 9. Clean 09_portfolio_holdings.csv

In [25]:
holdings = holdings.drop_duplicates()

holdings['portfolio_date'] = pd.to_datetime(
    holdings['portfolio_date'],
    errors='coerce'
)

cols = [
    'weight_pct',
    'market_value_cr',
    'current_price_inr'
]

for col in cols:
    holdings[col] = pd.to_numeric(
        holdings[col],
        errors='coerce'
    )

holdings = holdings[
    holdings['weight_pct'].between(0,100)
]

holdings.to_csv(
    "../data/processed/clean_portfolio_holdings.csv",
    index=False
)

## 10. Clean 10_benchmark_indices.csv

In [26]:
benchmark = benchmark.drop_duplicates()

benchmark['date'] = pd.to_datetime(
    benchmark['date'],
    errors='coerce'
)

benchmark = benchmark.sort_values('date')

numeric_cols = benchmark.columns.drop('date')

for col in numeric_cols:
    benchmark[col] = pd.to_numeric(
        benchmark[col],
        errors='coerce'
    )

benchmark = benchmark.ffill()

benchmark.to_csv(
    "../data/processed/clean_benchmark_indices.csv",
    index=False
)

# save all 10 cleaned CSV files

In [27]:
import os

# Create processed folder
os.makedirs("../data/processed", exist_ok=True)

# Save cleaned datasets
fund_master.to_csv("../data/processed/01_clean_fund_master.csv", index=False)

nav_history.to_csv("../data/processed/02_clean_nav_history.csv", index=False)

aum.to_csv("../data/processed/03_clean_aum_by_fund_house.csv", index=False)

sip.to_csv("../data/processed/04_clean_monthly_sip_inflows.csv", index=False)

category.to_csv("../data/processed/05_clean_category_inflows.csv", index=False)

folio.to_csv("../data/processed/06_clean_industry_folio_count.csv", index=False)

performance.to_csv("../data/processed/07_clean_scheme_performance.csv", index=False)

transactions.to_csv("../data/processed/08_clean_investor_transactions.csv", index=False)

holdings.to_csv("../data/processed/09_clean_portfolio_holdings.csv", index=False)

benchmark.to_csv("../data/processed/10_clean_benchmark_indices.csv", index=False)

print("All cleaned CSV files saved successfully.")

All cleaned CSV files saved successfully.

In [28]:
import os

print(os.listdir("../data/processed"))

['01_clean_fund_master.csv', '01_fund_master.csv', '02_clean_nav_history.csv', '02_nav_history.csv', '03_aum_by_fund_house.csv', '03_clean_aum_by_fund_house.csv', '04_clean_monthly_sip_inflows.csv', '04_monthly_sip_inflows.csv', '05_category_inflows.csv', '05_clean_category_inflows.csv', '06_clean_industry_folio_count.csv', '06_industry_folio_count.csv', '07_clean_scheme_performance.csv', '07_scheme_performance.csv', '08_clean_investor_transactions.csv', '08_investor_transactions.csv', '09_clean_portfolio_holdings.csv', '09_portfolio_holdings.csv', '10_benchmark_indices.csv', '10_clean_benchmark_indices.csv', 'clean_aum_by_fund_house.csv', 'clean_benchmark_indices.csv', 'clean_category_inflows.csv', 'clean_fund_master.csv', 'clean_industry_folio_count.csv', 'clean_investor_transactions.csv', 'clean_monthly_sip_inflows.csv', 'clean_nav.csv', 'clean_nav_history.csv', 'clean_performance.csv', 'clean_portfolio_holdings.csv', 'clean_scheme_performance.csv', 'clean_transactions.csv']

# Create SQLite Database

In [29]:
engine = create_engine("sqlite:///../data/bluestock_mf.db")

print("Database Created Successfully!")

Database Created Successfully!

In [30]:
fund_master.to_sql(
    "dim_fund",
    engine,
    if_exists="replace",
    index=False
)

nav_history.to_sql(
    "fact_nav",
    engine,
    if_exists="replace",
    index=False
)

aum.to_sql(
    "fact_aum",
    engine,
    if_exists="replace",
    index=False
)

sip.to_sql(
    "fact_sip_industry",
    engine,
    if_exists="replace",
    index=False
)

category.to_sql(
    "fact_category_inflows",
    engine,
    if_exists="replace",
    index=False
)

folio.to_sql(
    "fact_folio_count",
    engine,
    if_exists="replace",
    index=False
)

performance.to_sql(
    "fact_performance",
    engine,
    if_exists="replace",
    index=False
)

transactions.to_sql(
    "fact_transactions",
    engine,
    if_exists="replace",
    index=False
)

holdings.to_sql(
    "fact_portfolio",
    engine,
    if_exists="replace",
    index=False
)

benchmark.to_sql(
    "dim_benchmark",
    engine,
    if_exists="replace",
    index=False
)

print("All Tables Loaded Successfully!")

All Tables Loaded Successfully!

In [31]:
conn = sqlite3.connect("../data/bluestock_mf.db")
cursor = conn.cursor()
print("connected successfully.")

connected successfully.

In [32]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

tables = cursor.execute(query).fetchall()

print("Tables in Database:\n")

for table in tables:
    print(table[0])

Tables in Database:

dim_fund
fact_nav
fact_aum
fact_sip_industry
fact_category_inflows
fact_folio_count
fact_performance
fact_transactions
fact_portfolio
dim_benchmark

In [33]:
table_names = [
    "dim_fund",
    "fact_nav",
    "fact_aum",
    "fact_sip_industry",
    "fact_category_inflows",
    "fact_folio_count",
    "fact_performance",
    "fact_transactions",
    "fact_portfolio",
    "dim_benchmark"
]

for table in table_names:

    query = f"SELECT COUNT(*) FROM {table}"

    count = pd.read_sql(query, conn)

    print(table)

    print(count)

    print("-"*50)

dim_fund
   COUNT(*)
0        40
--------------------------------------------------
fact_nav
   COUNT(*)
0     46000
--------------------------------------------------
fact_aum
   COUNT(*)
0        90
--------------------------------------------------
fact_sip_industry
   COUNT(*)
0        48
--------------------------------------------------
fact_category_inflows
   COUNT(*)
0       144
--------------------------------------------------
fact_folio_count
   COUNT(*)
0        21
--------------------------------------------------
fact_performance
   COUNT(*)
0        40
--------------------------------------------------
fact_transactions
   COUNT(*)
0     32778
--------------------------------------------------
fact_portfolio
   COUNT(*)
0       322
--------------------------------------------------
dim_benchmark
   COUNT(*)
0      8050
--------------------------------------------------